# -*- coding: utf-8 -*-
"""inference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWA9SqogKXmp2hh22ysCL-Q92w-AnxTP
"""

import cv2
import time
from collections import deque
from ultralytics import YOLO


class HelmetDetectionSystem:
    def __init__(self, model_path, alert_delay=3.0, confidence_threshold=0.5):
        self.model = YOLO(model_path)
        self.alert_delay = alert_delay
        self.conf_threshold = confidence_threshold

        # this is for tracking alert state
        self.no_helmet_start_time = None
        self.alert_active = False

        # temporal smoothing
        self.history = deque(maxlen=5)

    def process_frame(self, frame):
        results = self.model.predict(frame, conf=self.conf_threshold, verbose=False)[0]
        boxes = results.boxes

        annotated = frame.copy()

        helmet_count = 0
        head_count = 0
        no_helmet_present = False

        # process all of the detections
        for box in boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0].cpu().numpy())
            cls = int(box.cls[0])
            conf = float(box.conf[0])

            label = "HELMET" if cls == 0 else "NO HELMET"
            color = (0, 255, 0) if cls == 0 else (0, 0, 255)

            if cls == 0:
                helmet_count += 1
            else:
                head_count += 1
                no_helmet_present = True

            cv2.rectangle(annotated, (x1, y1), (x2, y2), color, 2)
            cv2.putText(
                annotated,
                f"{label} {conf:.2f}",
                (x1, y1 - 8),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                color,
                2,
            )

        # temporal smoothing
        self.history.append(no_helmet_present)
        smoothed = sum(self.history) > len(self.history) / 2

        # defining our alert logic
        current = time.time()

        if smoothed:
            if self.no_helmet_start_time is None:
                self.no_helmet_start_time = current

            if (current - self.no_helmet_start_time) >= self.alert_delay:
                self.alert_active = True
        else:
            self.alert_active = False
            self.no_helmet_start_time = None

        # dashboard in top left of screen
        cv2.rectangle(annotated, (10, 10), (300, 150), (0, 0, 0), -1)
        cv2.putText(annotated, f"Helmets: {helmet_count}", (20, 40),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        cv2.putText(annotated, f"No Helmet: {head_count}", (20, 70),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)

        if self.alert_active:
            cv2.putText(annotated, "ALERT: NO HELMET!", (20, 110),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 3)
        else:
            cv2.putText(annotated, "Status: OK", (20, 110),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

        return annotated

    def run_webcam(self, cam_id=0):
        cap = cv2.VideoCapture(cam_id)

        if not cap.isOpened():
            print("Could not open webcam.")
            return

        print("Press 'q' to quit.")

        while True:
            ret, frame = cap.read()
            if not ret:
                break

            annotated = self.process_frame(frame)
            cv2.imshow("Helmet Detection System", annotated)

            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

        cap.release()
        cv2.destroyAllWindows()



# MAIN EXECUTION


MODEL_PATH = "/Users/tanner/helmet_model_weights/stage2_full_finetune_yolov8s_best.pt"

system = HelmetDetectionSystem(
    model_path=MODEL_PATH,
    alert_delay=3.0,
    confidence_threshold=0.5
)

system.run_webcam()